FROM osrf/ros:humble-desktop

# Evita interacción con apt
ENV DEBIAN_FRONTEND=noninteractive

# Instala dependencias básicas
RUN apt update && apt install -y \
    git \
    python3-pip \
    build-essential \
    ros-humble-gazebo-ros-pkgs \
    ros-humble-xacro \
    ros-humble-joint-state-publisher-gui \
    ros-humble-rmw-cyclonedds-cpp \
    ros-humble-tf-transformations \
    net-tools \
    nano \
    curl \
    wget \
    lsb-release \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# Instala PyYAML para scripts
RUN pip3 install pyyaml

# Crea el workspace dentro del contenedor (montaremos el real con volumen)
WORKDIR /TFG_ws

# Fuentes y entorno
SHELL ["/bin/bash", "-c"]
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

